# Generated by Django 3.1.7 on 2021-03-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_post_count_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(),
        ),
    ]
